"""Add train_state and stations_snapshot for historic data

Revision ID: bf7d202b044b
Revises: a3336e2e4220
Create Date: 2025-09-11 09:49:39.140317

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf7d202b044b"
down_revision: Union[str, Sequence[str], None] = "a3336e2e4220"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "trains", sa.Column("train_state", sa.String(length=20), nullable=True)
    )
    op.add_column("trains", sa.Column("stations_snapshot", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trains", "stations_snapshot")
    op.drop_column("trains", "train_state")
    # ### end Alembic commands ###
